---
title: "Intermediate Statistics"
---

**Instructor:** Evan Ray

**Email:** eray@mtholyoke.edu

**Office:** Clapp 404C

**Office Hours:** Regularly scheduled office hours at the times listed below.  These are times I guarantee I will be in my office and available, but I am also available by appointment at other times.

 * Wednesday 1:30PM-2:30PM
 * Thursday 9:00AM-11:00AM
 * Friday 12:30PM-1:30PM

**Extra Help:** We have a TA for this class, Sabirah Shuaybi.  She is fantastic.  There are two different ways you can meet with her:

1. She will hold regular office hours on **Thursday nights from 7-9pm in Clapp 420** as a time for group work.  You can also just use this space as a time and place to work with others in the class.
2. She is also available for individual one-on-one meetings on Wednesdays in the library atrium between 4 and 6 pm.  You can book an appointment with her directly on her calendar here: https://calendar.google.com/calendar/selfsched?sstoken=UUhkclh1ZWkyYXpDfGRlZmF1bHR8ODNlYmRlNGI4MzBkZWI2NDVlZTA0OTFmODMxMTlmNGU

**Piazza:** We have a Piazza page at [https://piazza.com/mtholyoke/spring2018/stat242](https://piazza.com/mtholyoke/spring2018/stat242).  You can ask and answer questions there, anonymously if you want, and everyone in the class will be able to see and contribute to the answers.

**Syllabus:** [pdf](syllabus/syllabus_stat_242.pdf)

Please use the navigation menu above to go to the schedule, homework assignments, and materials related to quizzes and exams.
