---
title: "Schedule"
---

**Click on the text like "Week 1: Jan 22 -- 25" to expand or collapse the items we covered in that week.**

I will fill in more detail and provide links to lecture notes and labs as we go along.  Items for future dates are tentative and subject to change.

```{r, echo = FALSE}
make_week_box <- function(id, open, title, contents) {
  cat('
<div class="panel panel-default">
<div class="panel-heading" role="tab" id="headingOne">
<h5 class="mb-0">
<a data-toggle="collapse" href="#',
id,
'" aria-expanded="true" aria-controls="collapseOne">
',
title,
'</a>
</h5>
</div>

<div id="',
id,
'" class="collapse',
ifelse(open, " in", ""),
'">
<div class="panel-body">
',
contents,
'
</div>
</div>
</div>',
  sep = "")
}
```

```{r, echo = FALSE, results='asis'}
make_week_box("week1", FALSE, "Week 1: Jan 22 -- 25",
"
* Introduction; review of topics from our intro. statistics course; getting started with R

#### Wed, Jan 23

 * **In class**, we will work on: Introduction and Chapter 1
    * Discuss the syllabus; course overview.
    * Foundations of statistical inference; Chapter 1 of the Statistical Sleuth.  [pdf](materials/20190123_intro/foundations_inference.pdf)
 * **After class**, please do the following:
    * **Register for GitHub** [here](https://github.com) if you haven't already; I will ask you to provide your GitHub user name in the questionairre below.
    * **Fill out** a brief [questionnairre](https://goo.gl/forms/Z0nYaD3IxOx25Jum2)
    * **Fill out** this brief [poll about when my office hours should be held](http://whenisgood.net/n4ahdz3)
    * **Sign up** for our class at Piazza (anonymous question and answer forum): [https://piazza.com/mtholyoke/spring2019/stat242](https://piazza.com/mtholyoke/spring2019/stat242)
    * **Read** Chapter 1 and Sections 2.1 and 2.2 of our book.

#### Fri, Jan 25
 * **In class**, we will work on: Chapter 1
    * Finish lab/example from day 1; a first look at R
    * Look over quizzes on material from Chapter 1
    * If you have extra time, start working through the data camp assignment
 * **After class**, please do the following:
    * **Homework 0** is on DataCamp, due Wed Jan 30.
    * Start working on **Homework 1**, due Fri Feb 1.
    * **Read** Chapter 1 and Sections 2.1 and 2.2 of our book.
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week2", FALSE, "Week 2: Jan 28 -- Feb 1",
"
Chapter 2

#### Mon, Jan 28
 * **In Class**, we will do the following: Start on Sections 2.1, 2.2, and 2.5
    * **Quiz**
    * t-based inference for a single mean or a difference between two means with paired data.
        * Overview of concepts behind $t$ tests and confidence intervals [pdf](materials/20190128_t/t_summary.pdf)
        * Examples of $t$ tests and confidence intervals [pdf](materials/20190128_t/t.pdf)
 * **After class**, please do the following:
    * **Homework 0** is on DataCamp, due Wed Jan 30.
    * Start working on **Homework 1**, due Fri Feb 1.
    * **Read** Chapter 1 and Sections 2.1 and 2.2 of our book.

#### Wed, Jan 30
 * **In Class**, we will do the following: Finish Sections 2.1, 2.2, and 2.5
    * **Quiz**
    * Finish working through the handouts from Monday.
 * **After class**, please do the following:
    * Work on **Homework 1**, due Friday Feb 1.

#### Fri, Feb 1
 * **In Class**, we will do the following:
    * **No Quiz**
    * Finish working through the handouts from Monday and Wednesday.
 * **After class**, please do the following:
    * Work on **Homework 2**, due Friday Feb 8.
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week3", FALSE, "Week 3: Feb 4 -- 8",
"

#### Mon, Feb 4
 * **In Class**, we will do the following:
    * **Quiz** on material from Chapter 1
    * Degrees of freedom
        * All you really need to know is that degrees of freedom is sample size minus number of parameters for the mean
        * More detail here: [pdf](materials/20190204_anova/degrees_of_freedom.pdf)
    * Discuss material from Sections 2.3, 5.2 and 6.2.  [pdf](materials/20190204_anova/anova_pairwise.pdf)
 * **After class**, please do the following:
    * Work on **Homework 2**, due Friday Feb 8.

#### Wed, Feb 6
 * **In Class**, we will do the following:
    * **Quiz** on material from Chapter 2
    * Material from Sections 2.3, 5.2 and 6.2
 * **After class**, please do the following:
    * Work on **Homework 2**, due Friday Feb 8.

#### Fri, Feb 8
 * **In class**, we will do the following:
    * **Quiz** on material from Chapter 1 or Chapter 2
    * Material from Sections 2.3, 5.2 and 6.2
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week4", FALSE, "Week 4: Feb 11 -- 15",
"

#### Mon, Feb 11
 * **In class**, we will do the following:
    * **Quiz** on material from Chapter 1 or Chapter 2; **not** on Sections 5.2 and 6.2
    * Wrap up material from Sections 2.3, 5.2, and 6.2

#### Wed, Feb 13
 * **In class**, we will do the following:
    * **Quiz** on material from Chapter 1, Chapter 2, or Sections 5.2 and 6.2
    * Discuss material from Section 5.3: [pdf](materials/20190213_F/anova_F.pdf)

#### Fri, Feb 15
 * **In class**, we will do the following:
    * **Quiz** on material from Chapter 1, Chapter 2, or Sections 5.2 and 6.2
    * Discuss material from Sections 5.3 and 5.4: [pdf](materials/20190215_F/anova_F.pdf)
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week5", FALSE, "Week 5: Feb 18 -- 22",
"

#### Mon, Feb 18
 * **In class**, we will do the following:
    * **Quiz**
    * Discuss material from Sections 5.3 and 5.4: [pdf](materials/20190218_F/F_examples.pdf)
    * Lab 4.  Solutions: [pdf](https://github.com/mhc-stat242-s2019/Lab4_solutions/blob/master/lab04_anova_F.pdf)
 * **After class**, please work on:
    * Read Section 5.5 and Chapter 3
    * **Homework 4** due Friday, Feb 22

#### Wed, Feb 20
 * **In class**, we will do the following:
    * **Quiz**
    * Discuss material from Section 5.5 and Chapter 3: Conditions for ANOVA [pdf](materials/20190220_conditions/anova_conditions.pdf)
    * **Homework 4** due Friday, Feb 22

#### Fri, Feb 22
 * **Homework 4** due today!!
 * **In class**, we will do the following:
    * Discuss material from Section 5.5 and Chapter 3
        * Handout 1: [pdf](materials/20190222_transformations/anova_transformations.pdf)
        * Handout 2: [pdf](materials/20190222_transformations/transformations.pdf)
    * Lab 5.  Solutions: [pdf](https://github.com/mhc-stat242-s2019/Lab5_solutions/blob/master/lab05_anova_transformations.pdf)
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week6", FALSE, "Week 6: Feb 25 -- Mar 1",
"

#### Mon, Feb 25
 * **In class**, we will do the following:
    * **Quiz**
    * Section 6.3 and parts of 6.4.  [pdf](materials/20190225_multiple_comparisons/multiple_comparisons.pdf)
    * Lab 6 on GitHub.  Solutions: [pdf](https://github.com/mhc-stat242-s2019/Lab6_solutions/blob/master/lab06_multiple_comparisons.pdf)
 * **After class** please work on the following:
    * **Homework 5** due Friday Mar 1

#### Wed, Feb 27
 * **In class**, we will do the following:
    * **Quiz**
    * Review solutions for Lab 6
    * Start on \"Simple\" Linear Regression: [pdf](materials/20190227_SLR/20190227_slr.pdf)
    * If time, Lab 7: [https://github.com/mhc-stat242-s2019/Lab7.git](https://github.com/mhc-stat242-s2019/Lab7.git)
 * **After class** please work on the following:
    * **Homework 5** due Friday Mar 1

#### Fri, Mar 1
 * **In class**, we will do the following:
    * **Quiz**
    * Chapter 7
        * Finish handout from last class
        * Point estimates and confidence intervals for the mean response at a given value of the explanatory variable: [pdf](materials/20190301_predict/20190301_predict.pdf)
        * Start Lab 7
 * **After class** please work on the following:
    * **Homework 5** due Friday Mar 1
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week7", FALSE, "Week 7: Mar 4 -- 8",
"

#### Mon, Mar 4
 * **In class**, we will do the following:
    * **Quiz**
    * Finish Lab 7.  Solutions posted here: https://github.com/mhc-stat242-s2019/Lab7_Solutions

#### Wed, Mar 6
 * **In class**, we will do the following:
    * Midterm

#### Fri, Mar 8
 * **Class cancelled**
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week8", FALSE, "Week 8: Mar 11 -- 15",
"
#### Spring Break: safe travels!
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week9", FALSE, "Week 9: Mar 18 -- 22",
"

#### Mon, Mar 18
 * **In class**, we will do the following: Start thinking about residuals.  Chapters 7 and 8
    * **No Quiz**
    * Residuals, model fit by least squares, prediction intervals: [pdf](materials/20190318_SLR_residuals/20190318_residuals.pdf)
    * Talk through Chapter 7 quizzes

#### Wed, Mar 20
 * **In class**, we will do the following: Chapter 8
    * **Quiz**
    * Need to make plots before fitting models!!
        * Part 1: [pdf](materials/20190318_SLR_residuals/20190318_anscombe_fit_summaries.pdf)
        * Part 2: [pdf](materials/20190318_SLR_residuals/20190318_anscombe_residuals.pdf)
    * Start on transformations for simple linear regression
        * Example/handout: [pdf](materials/20190320_SLR_conditions_transformations/slr_transformations.pdf)
        * Lab 8.  Solutions here: https://github.com/mhc-stat242-s2019/Lab8_solutions/blob/master/lab08_slr_transformations.pdf

#### Fri, Mar 22
 * **In class**, we will do the following: Chapter 8
    * **Quiz**
    * More on transformations for simple linear regression
        * Lab 9.  Solutions here: https://github.com/mhc-stat242-s2019/Lab9_solutions/blob/master/lab09_more_slr_transformations.pdf
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week10", FALSE, "Week 10: Mar 25 -- 29",
"

#### Mon, Mar 15
 * **In class**, we will do the following:
    * **Quiz**
    * A couple more minor topics from Chapter 8: refining our view of equal standard deviations, handling outliers (we will revisit in Chapter 11), and checking normality [pdf](materials/20190325_slr_conditions_quadratic/slr_conditions_misc.pdf)

#### Wed, Mar 27
 * **In Class**, we will do the following:
    * **Quiz**
    * Chapters 9 and 10: Multiple regression with 1 categorical and 1 quantitative explanatory variable (2 parallel lines): [pdf](materials/20190327_two_lines/20190327_two_parallel_lines.pdf)
    * Lab 10

#### Fri, Mar 29
 * **In Class**, we will do the following:
    * **Quiz**
    * Chapters 9 and 10: Interactions between a categorical and quantitative variable (2 non-parallel lines): [pdf](materials/20190329_more_two_lines/20190329_two_lines.pdf)
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week11", FALSE, "Week 11: Apr 1 -- 5",
"

#### Mon, Apr 1
 * **In Class**, we will do the following:
    * **Quiz**
    * Chapters 9 and 10: Regression with more than two lines: [pdf](materials/20190401_gt2_categories/20190401_gt2_categories.pdf)

#### Wed, Apr 3
 * **In Class**, we will do the following:
    * **No Quiz**
    * Time to work through quizzes on regression with multiple lines

#### Fri, Apr 5
 * **In Class**, we will do the following:
    * **Class Cancelled**
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week12", TRUE, "Week 12: Apr 8 -- 12",
"

#### Mon, Apr 8
 * **In Class**, we will do the following:
    * **Quiz**
    * Highlights from Chapter 13: 2 way ANOVA.  [pdf](materials/20190402_2_way_anova/20190403_2_way_anova.pdf)

#### Wed, Apr 10
 * **In Class**, we will do the following:
    * **Quiz**
    * Lab 11: 2 way ANOVA
        * Solutions [here](https://github.com/mhc-stat242-s2019/Lab11_solutions/blob/master/lab11_2_way_anova.pdf)

#### Fri, Apr 12
 * **In Class**, we will do the following:
    * **Midterm 2**
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week13", TRUE, "Week 13: Apr 15 -- 19",
"
#### Mon, Apr 15
 * **In Class**, we will do the following:
    * Wrap up/answer questions on 2 way ANOVA lab (Lab 11)
    * **Quiz**
    * Quadratic Regression: [pdf](materials/20190415_quadratic_reg/20190415_quadratic_reg.pdf)
    * Lab 12.

#### Wed, Apr 17
 * **In Class**, we will do the following:
    * **Quiz**
    * Diagnostics for outliers/high leverage observations: [pdf](materials/20190417_regression_diagnostics/20190417_residual_diagnostics.pdf)
    * Start on multiple regression, pairs plots, added variable plots: [pdf](materials/20190417_regression_diagnostics/20190417_avPlots.pdf)

#### Fri, Apr 19
 * **In Class**, we will do the following:
    * **Quiz**
    * Finish handouts from April 17
    * Lab 13
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week14", FALSE, "Week 14: Apr 22 -- 26",
"

#### Mon, Apr 22
 * **In Class**, we will do the following:
    * **Quiz**

#### Wed, Apr 24
 * **In Class**, we will do the following:
    * **Quiz**

#### Fri, Apr 26
 * **In Class**, we will do the following:
    * **Quiz**
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week15", FALSE, "Week 15: Apr 29 -- 30",
"

#### Mon, Apr 29
 * **In Class**, we will do the following:
    * **Quiz**
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("finals", TRUE, "Final Exams: Fri, May 3 at 7pm -- Tue, May 7 at noon",
"We will have a cumulative final exam.
"
  )
```
